# Goal 
geometry_msgs/PoseStamped pose
---
# Result
bool success
float64 final_distance
float64 final_angle_error
---
# Feedback
geometry_msgs/PoseStamped current_pose
float64 distance_remaining
float64 angle_remaining
float64 elapsed_time
