go_to_goal_server:
  ros__parameters:
    control_rate: 20.0
    kv: 1.3
    kw: 1.15
    v_max: 0.5
    w_max: 3.0
    position_tolerance: 0.05
    align_tolerance: 0.0174
    orient_tolerance: 0.0174
    realign_threshold: 0.5
